Fix Mapping for 1.7 clusters
When running tests against 1.7, we can get messages like:

```
REPRODUCE WITH:
mvn test -Dtests.seed=5C3E450B6EA83BBF -Dtests.class=fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerImplAllParametersIT -Dtests.method="test_filesize_nolimit" -Dtests.locale=pt -Dtests.timezone=Africa/Kampala

org.elasticsearch.client.ResponseException: PUT http://127.0.0.1:9400/fscrawler_test_filesize_nolimit/_mapping/doc: HTTP/1.1 400 Bad Request
{"error":"ElasticsearchParseException[Failed to parse content to map]; nested: JsonParseException[Unexpected character ('\"' (code 34)): was expecting comma to separate OBJECT entries\n at [Source: org.elasticsearch.common.compress.lzf.LZFCompressedStreamInput@7363ab4a; line: 31, column: 12]]; ","status":400}
```

Was introduced by #183

Closes #259.