Adding new files while scanning could raise a non caught exception
 This patch tries to reduce that risk although it does not totally removes it.

 When adding a new file to the directory which is scanned by the river could fail when closing the river at the same time.

 We need to check if the river is still opened before adding anything to the bulk and fail with a clean message otherwise.

 That kind of error could appear as well:

 ```
 2014-08-11 13:06:56,398 WARN  - [node_1] [fs][test_stop_river] failed to get _lastupdate, throttling....
 org.elasticsearch.ElasticsearchIllegalStateException: Future got interrupted
 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:48)
 	at fr.pilato.elasticsearch.river.fs.river.FsRiver$FSParser.getLastDateFromRiver(FsRiver.java:440)
 	at fr.pilato.elasticsearch.river.fs.river.FsRiver$FSParser.run(FsRiver.java:404)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.InterruptedException
 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:274)
 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:113)
 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:45)
 	... 3 more
 ```

 Or that ones as well:

 ```
 2014-08-11 13:16:56,593 WARN  - [node_4] [fs][test_stop_river] Error while indexing content from /Users/dpilato/Documents/Elasticsearch/dev/fsriver/target/test-classes/test_stop_river
 2014-08-11 13:16:56,595 DEBUG - [node_4] [fs][test_stop_river] Exception for /Users/dpilato/Documents/Elasticsearch/dev/fsriver/target/test-classes/test_stop_river is org.elasticsearch.ElasticsearchIllegalStateException: Future got interrupted
 2014-08-11 13:10:42,776 INFO  - [node_0] [_river] update_mapping [test_stop_river] (dynamic)
 2014-08-11 13:10:42,797 WARN  - [node_2] [_river] no index mapper found for field: [fs.docadded] returning default postings format
 2014-08-11 13:10:42,798 WARN  - [node_2] [_river] no index mapper found for field: [fs.docdeleted] returning default postings format
 2014-08-11 13:10:42,799 WARN  - [node_2] [_river] no index mapper found for field: [fs.feedname] returning default postings format
 2014-08-11 13:10:42,799 WARN  - [node_2] [_river] no index mapper found for field: [fs.lastdate] returning default postings format
 ```

 or

 ```
 2014-08-11 14:22:29,757 WARN  - [node_1] [fs][test_stop_river] Error executing bulk
 java.lang.InterruptedException
 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
 	at java.util.concurrent.Semaphore.acquire(Semaphore.java:317)
 	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:288)
 	at org.elasticsearch.action.bulk.BulkProcessor.executeIfNeeded(BulkProcessor.java:267)
 	at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:249)
 	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:236)
 	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:232)
 	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:218)
 	at fr.pilato.elasticsearch.river.fs.river.FsRiver$FSParser.esIndex(FsRiver.java:863)
 	at fr.pilato.elasticsearch.river.fs.river.FsRiver$FSParser.indexFile(FsRiver.java:779)
 	at fr.pilato.elasticsearch.river.fs.river.FsRiver$FSParser.addFilesRecursively(FsRiver.java:536)
 	at fr.pilato.elasticsearch.river.fs.river.FsRiver$FSParser.run(FsRiver.java:410)
 	at java.lang.Thread.run(Thread.java:745)
 ```

 Closes #75.