Elasticsearch node settings should not be null by default
[The documentation](https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#node-settings) says that `elasticsearch.nodes` have a default value of `http://127.0.0.1:9200`.

It's not the case when you run a job like:

```yaml
---
name: "rest"
fs:
  url: "/tmp/es"
elasticsearch:
  username: "elastic"
  password: "changeme"
```

This fails with:

```
11:14:38,083 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client on Elasticsearch{nodes=null, index='rest', indexFolder='rest_folder', bulkSize=100, flushInterval=5s, byteSize=10mb, username='null', pipeline='null', pathPrefix='null', sslVerification='true'}, disabling crawler...
11:14:38,083 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "fr.pilato.elasticsearch.crawler.fs.settings.Elasticsearch.getNodes()" is null
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.buildRestClient(ElasticsearchClientV7.java:426) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:151) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.start(FsCrawlerManagementServiceElasticsearchImpl.java:60) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl.start(FsCrawlerImpl.java:116) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.startEsClient(FsCrawlerCli.java:307) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:283) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
```

The only workaround is:

```yaml
---
name: "rest"
fs:
  url: "/tmp/es"
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  username: "elastic"
  password: "changeme"
```

Closes #1191.